version: "3.0"

services:
  linebot:
    build: .
    restart: always
    tty: true
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/python_modules
    entrypoint: >
      sleep 86400